creation_rules:
  - path_regex: vault\.yml$
    kms: arn:aws:kms:us-east-1:584274110661:alias/homelab-cicd-kms
  - path_regex: secrets\.yaml$
    kms: arn:aws:kms:us-east-1:584274110661:alias/homelab-cicd-kms
