---
- name: include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: install Java dependencies
  package:
    name: "{{ dependencies }}"
    state: present
