ungrouped:
    hosts:
        localhost:
            vars:
                ansible_connection: local
                ansible_python_interpreter: '{{ansible_playbook_python}}'
rpis:
    hosts:
        brrpi1: null
        brrpi2: null
        brrpi3: null
swarm:
    hosts:
        brrpi1: null
        brrpi2: null
        brrpi3: null
homelab:
    hosts:
        nas:
            ansible_python_interpreter: /volume1/@appstore/python310/bin/python3
            ansible_user: mestruble
            ansible_become: true
            ansible_host: yggdrasil
    children:
        swarm: null
