---
- name: Ensure Fail2Ban Installed
  package:
    name: fail2ban
    state: present
    update_cache: true

- name: Ensure cfuser is set
  ansible.builtin.lineinfile:
    path: /etc/fail2ban/action.d/cloudflare.conf
    regexp: "^cfuser="
    line: "cfuser={{ cfuser }}"

- name: Ensure cftoken is set
  ansible.builtin.lineinfile:
    path: /etc/fail2ban/action.d/cloudflare.conf
    regexp: "^cftoken="
    line: "cftoken={{ cftoken }}"

- include: jail.yml
