---
plugin: amazon.aws.aws_ec2

keyed_groups:
  - key: tags.Name
    separator: ""

  - key: instance_type
    separator: ""

  - key: tags.Namespace
    separator: ""

  - key: tags.Environment
    separator: ""

  - key: tags.Stage
    separator: ""

filters:
  instance-state-name: running

compose:
  ansible_host: public_ip_address
  instance_type: instance_type
