---
- name: Get list of accounts
  become: true
  ansible.builtin.command: "/usr/syno/sbin/synouser -enum all"
  changed_when: false
  register: synusers_list

- name: "Create account {{ add_nas_user_account }}"
  when: add_nas_user_account not in synusers_list.stdout_lines
  ansible.builtin.command:
    argv:
      - "/usr/syno/sbin/synouser"
      - "--add {{ add_nas_user_account | quote }}"
      - "{{ add_nas_user_password | quote }}"
      - "{{ add_nas_user_comment | quote }}"
      - "0"
      - "{{ add_nas_user_email | quote }}"
      - "{{ add_nas_user_privilege | quote }}"

- name: "Set group for {{ add_nas_user_account }}"
  when: add_nas_user_groups is defined
  ansible.builtin.command: "/usr/syno/sbin/synogroup --memberadd {{ group }} {{ add_nas_user_account }}"
  loop: "{{ add_nas_user_groups }}"
  loop_control:
    loop_var: group

- name: "Check homedir is existing for {{ add_nas_user_account }}"
  when: add_nas_user_create_home
  ansible.builtin.command: /usr/syno/sbin/synouser -get {{ add_nas_user_account | quote}} | grep \"User Dir\" | grep -E -o \"\[(.*?)\]\"
  ignore_errors: true
  changed_when: false
  register: add_nas_user_home_dir

- ansible.builtin.debug:
    var: add_nas_user_home_dir

- name: "Create account home directory for {{ add_nas_user_account }}"
  when: ( add_nas_user_home_dir.stdout | length ) == 0 and add_nas_user_create_home
  ansible.builtin.command: "/usr/syno/bin/synouserhome --prepare-folder {{ add_nas_user_account | quote }}"
