---
- name: Get list of accounts
  become: true
  ansible.builtin.command: "/usr/syno/sbin/synouser -enum all"
  changed_when: false
  register: synusers_list

- name: "Create account {{ add_nas_user_account }}"
  when: add_nas_user_account not in synusers_list.stdout_lines
  ansible.builtin.command:
    argv:
      - "/usr/syno/sbin/synouser"
      - "--add {{ add_nas_user_account | quote }}"
      - "{{ add_nas_user_password | quote }}"
      - "{{ add_nas_user_comment | quote }}"
      - "0"
      - "{{ add_nas_user_email | quote }}"
      - "{{ add_nas_user_privilege | quote }}"

- name: "Set group for {{ add_nas_user_account }}"
  when: add_nas_user_groups is defined
  ansible.builtin.command: "/usr/syno/sbin/synogroup --memberadd {{ group }} {{ add_nas_user_account }}"
  loop: "{{ add_nas_user_groups }}"
  loop_control:
    loop_var: group

- name: "Get syno user info for {{ add_nas_user_account }}"
  when: add_nas_user_create_home
  ansible.builtin.command: /usr/syno/sbin/synouser -get {{ add_nas_user_account }} #| grep 'User Dir' | grep -E -o '\[(.*?)\]'
  ignore_errors: true
  changed_when: false
  register: synouser_info

- name: "Extract existing home directory path for {{ add_nas_user_account }}"
  when: add_nas_user_create_home
  ansible.builtin.set_fact:
    add_nas_user_home_dir: "{{ synouser_info.stdout | regex_search('.*?Dir.*?\\[(.*?)\\]', '\\1', multiline=True) | list | first | trim}}"

- name: "Create account home directory for {{ add_nas_user_account }}"
  when: ( add_nas_user_home_dir | length ) == 0 and add_nas_user_create_home
  ansible.builtin.command: "/usr/syno/bin/synouserhome --prepare-folder {{ add_nas_user_account | quote }}"

- name: "Get syno updated user info for {{ add_nas_user_account }}"
  when: ( add_nas_user_home_dir | length ) == 0 and add_nas_user_create_home
  ansible.builtin.command: /usr/syno/sbin/synouser -get {{ add_nas_user_account }} #| grep 'User Dir' | grep -E -o '\[(.*?)\]'
  ignore_errors: true
  changed_when: false
  register: synouser_info

- name: "Register user home directory for {{ add_nas_user_account }}"
  when: ( add_nas_user_home_dir | length ) == 0 and add_nas_user_create_home
  ansible.builtin.set_fact:
    add_nas_user_home_dir: "{{ synouser_info.stdout | regex_search('.*?Dir.*?\\[(.*?)\\]', '\\1', multiline=True) | list | first | trim}}"
